### PR TITLE
Added TVs + functionality of build process (before/after) for installation and update

### PR DESCRIPTION
**Pull request by timo-schlotmann**
All very experimental, for us it just has to work at the moment

### CODE REVIEW

**Comment by timo-schlotmann** [comment]
Take a look at this test configuration (The type of TemplateVars must be called tvtype):

{
    "name": "Mypackage",
    "lowCaseName": "mypackage",
    "description": "a simple app",
    "author": "@webevolutions",
    "version": "1.1.1",

    "templateVars": [{
        "name": "Mypackage-Tv-1",
        "caption": "Mypackage-Tv-1",
        "tvtype": "text",
        "description": "Tv 1",
        "sortOrder": "1",
        "defaultValue": "Test",
        "display": "",
        "templates": [
            "Mypackage-Template-1"
        ],
        "outputProperties": {},
        "inputProperties": {
            "allowBlank": "true",
            "minLength": "3"
        },
        "inputOptionValues": "",
        "properties": []
    }],

    "templates": [
        {
            "name": "Mypackage-Template-1",
            "file": "template-1.template.html",
            "description": "Template 1",
            "properties": []
        },
        {
            "name": "Mypackage-Template-2",
            "file": "template-2.template.html",
            "description": "Template 2",
            "properties": []
        }
    ],
    "chunks": [
        {
            "name": "Mypackage-Chunk-1",
            "file": "chunk-1.chunk.html"
        },
        {
            "name": "Mypackage-Chunk-2",
            "file": "chunk-2.chunk.html"
        }
    ],
    "snippets": [
        {
            "name": "Mypackage-Snippet-1",
            "file": "snippet-1.snippet.php",
            "properties": [
                {
                    "name": "name snippet 1",
                    "desc": "desc snippet 1",
                    "type": "textfield",
                    "options": "",
                    "value": "value snippet 1",
                    "lexicon": "package:test",
                    "area": ""
                }
            ]
        }
    ],
    "systemSettings": [
        {
            "key": "global_setting_1",
            "value": "A",
            "type": "textfield",
            "area": "settings global"
        },
        {
            "key": "global_setting_2",
            "value": "B",
            "type": "textfield",
            "area": "settings global"
        }
    ],

    "database": {
        "tables": [
            "Mypackage\\Model\\MYPCategories"
        ]
    },

    "build": {
        "readme": "core/components/mypackage/docs/readme.txt",
        "changelog": "core/components/mypackage/docs/changelog.txt",
        "license": "core/components/mypackage/docs/license.txt",
        "scriptsAfter": [
            "build.scripts.php"
        ]
    },

    "install": {
        "scriptsAfter": [
            "dev.scripts.php"
        ]
    },

    "update": {
        "scriptsAfter": [
            "dev.scripts.php"
        ]
    }
}

**Comment by JoshuaLuckers** [comment]
@theboxer what's your opinion on this PR? I would love to see TV's back in GPM for MODX 3.x!

**Comment by matdave** [comment]
This is helpful; however, the code needs to be cleaned up a bit. There are many unnecessary comments and commented out items. Personally, I generally use "commit" messages as the comments for items and use something like Git Tool Box to see when something was added and what it's reasoning was through comment history.

**Comment by theboxer** [comment]
Closing in favour of 27bfe0dd9cdf0ab4fca4d04e74c778fe2c160b50

**Pull request closed without merging**
